project_name: kubecarga

release:
  github:
    owner: Tech-Preta
    name: kubecarga

builds:
  - main: ./cmd/kubecarga/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-s -w -X main.version={{.Version}}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - images:
      - nataliagranato/kubecarga:latest
    dockerfile: Dockerfile

nfpms:
  - formats:
      - deb
      - rpm
    dependencies:
      - bash
    contents:
      - src: ./config.yaml
        dst: /etc/kubecarga/config.yaml
