name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]
        steps:
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.x'
        - name: Install dependencies
          run: go get k8s.io/client-go/kubernetes
        - name: Install dependencies  
          run:  go get k8s.io/client-go/rest
        - name: Install dependencies  
          run:  go get k8s.io/client-go/tools/clientcmd