name: Creating a release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: unshallow
        run: git fetch --prune --unshallow

      - name: clean artifacts
        run: rm -rf dist

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.10.3 # Especifique uma versão estável
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
